workflows:
  maui-android:
    name: Dotnet MAUI Android
    max_build_duration: 120
    instance_type: mac_mini_m1
    environment:
      android_signing:
        - ba7besh_beta
      groups:
        - google_play
      vars:
        DOTNET_PATH: $CM_BUILD_DIR/dotnet
        DOTNET: $CM_BUILD_DIR/dotnet/dotnet
        PACKAGE_NAME: "com.fastorg.ba7besh"
    scripts:
      - name: Install dotnet sdk
        script: | 
          wget https://dot.net/v1/dotnet-install.sh
          chmod +x dotnet-install.sh
          ./dotnet-install.sh --install-dir $DOTNET_PATH --version 7.0.300
      - name: Install MAUI
        script: | 
          $DOTNET nuget locals all --clear 
          $DOTNET workload install android maui   
      - name: Build
        script: | 
          UPDATED_BUILD_NUMBER=$BUILD_NUMBER
          $DOTNET publish -f net7.0-android \
            -c Release \
            -p:AndroidKeyStore=True \
            -p:AndroidSigningKeyStore=$CM_KEYSTORE_PATH \
            -p:AndroidSigningKeyAlias=$CM_KEY_ALIAS \
            -p:AndroidSigningKeyPass=$CM_KEY_PASSWORD \
            -p:AndroidSigningStorePass=$CM_KEYSTORE_PASSWORD \
            -p:ApplicationVersion=$UPDATED_BUILD_NUMBER \
            -p:ApplicationDisplayVersion="1.0.0" \
            -o ../artifacts
    artifacts:
        - /Users/builder/clone/artifacts/*Signed.aab
    publishing:
      slack:
        channel: '#mobile-team'
        notify_on_build_start: true
        notify:
          success: true
          failure: true
        