name: CI Build

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read

env:
  DOTNET_NOLOGO: true                     # Disable the .NET logo
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true # Disable the .NET first time experience
  DOTNET_CLI_TELEMETRY_OPTOUT: true       # Disable sending .NET CLI telemetry

jobs:
# MAUI Android Build
  build-android:
    runs-on: windows-2022
    name: Android Build
    steps:

      - name: Notify the mobile team - build started
        id: slack
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # mobile-team channel id
          channel-id: 'C058KACR6H4'
          slack-message: "GitHub build started: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
          
      - name: Install MAUI Workload
        run: dotnet workload install maui --ignore-failed-sources

      - name: Restore Dependencies
        run: dotnet restore ./bahbashApp/bahbashApp.csproj

      - name: Build MAUI Mobile App
        run: dotnet build ./bahbashApp/bahbashApp.csproj -bl:mobile.binlog

      - name: Build and Run UnitTests
        shell: bash
        run: |
          dotnet build ./bahbashApp.Tests/bahbashApp.Tests.csproj
          dotnet test ./bahbashApp.Tests/bahbashApp.Tests.csproj --no-build --verbosity normal

      - name: Upload Archive build log
        uses: actions/upload-artifact@v3
        with:
          name: logs
          path: '*.binlog'
      
      - name: Notify the mobile team - build result
        uses: slackapi/slack-github-action@v1.24.0
        with:
          # mobile-team channel id
          channel-id: 'C058KACR6H4'
          slack-message: "GitHub build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

      
